import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:tailorsync_v2/core/utils/snackbar_util.dart';
import 'package:tailorsync_v2/features/community/models/community_post.dart';
import 'package:tailorsync_v2/features/community/repositories/community_repository.dart';

class CreatePostScreen extends ConsumerStatefulWidget {
  const CreatePostScreen({super.key});

  @override
  ConsumerState<CreatePostScreen> createState() => _CreatePostScreenState();
}

class _CreatePostScreenState extends ConsumerState<CreatePostScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _contentController = TextEditingController();
  final _budgetController = TextEditingController();
  
  String _postType = 'discussion'; // 'discussion' or 'job_offer'
  bool _isLoading = false;

  @override
  void dispose() {
    _titleController.dispose();
    _contentController.dispose();
    _budgetController.dispose();
    super.dispose();
  }

  Future<void> _submit() async {
    if (!_formKey.currentState!.validate()) return;

    setState(() => _isLoading = true);

    try {
      final user = Supabase.instance.client.auth.currentUser;
      if (user == null) throw Exception('Not signed in');

      final budgetText = _budgetController.text.replaceAll(',', '');
      final budget = double.tryParse(budgetText) ?? 0.0;

      final post = CommunityPost(
        id: '', // Will be generated by DB
        userId: user.id,
        postType: _postType,
        title: _titleController.text.trim(),
        content: _contentController.text.trim(),
        budget: _postType == 'job_offer' ? budget : 0.0,
        status: 'open',
        createdAt: DateTime.now(),
      );

      final repo = ref.read(communityRepositoryProvider);
      await repo.createPost(post);

      if (mounted) {
        showSuccessSnackBar(context, 'Post created successfully!');
        Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        showErrorSnackBar(context, 'Error creating post: $e');
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('New Post'),
      ),
      body: Form(
        key: _formKey,
        child: SingleChildScrollView(
          padding: const EdgeInsets.all(16.0),
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // Post Type Toggle
              SegmentedButton<String>(
                segments: const [
                  ButtonSegment(value: 'discussion', label: Text('Discussion'), icon: Icon(Icons.forum)),
                  ButtonSegment(value: 'job_offer', label: Text('Job Offer'), icon: Icon(Icons.work)),
                ],
                selected: {_postType},
                onSelectionChanged: (Set<String> newSelection) {
                  setState(() {
                    _postType = newSelection.first;
                  });
                },
              ),
              const SizedBox(height: 24),

              TextFormField(
                controller: _titleController,
                decoration: const InputDecoration(labelText: 'Title', hintText: 'What is this about?'),
                validator: (v) => v == null || v.trim().isEmpty ? 'Please enter a title' : null,
              ),
              const SizedBox(height: 16),

              if (_postType == 'job_offer') ...[
                TextFormField(
                  controller: _budgetController,
                  keyboardType: TextInputType.number,
                  decoration: const InputDecoration(labelText: 'Estimated Budget (₦)', hintText: 'Optional'),
                ),
                const SizedBox(height: 16),
              ],

              TextFormField(
                controller: _contentController,
                maxLines: 6,
                decoration: InputDecoration(
                  labelText: _postType == 'job_offer' ? 'Job Description' : 'Message',
                  hintText: _postType == 'job_offer' 
                      ? 'Describe what you need a tailor to make...' 
                      : 'Share your thoughts, ask a question, or post a tip...',
                  alignLabelWithHint: true,
                ),
                validator: (v) => v == null || v.trim().isEmpty ? 'Please enter content' : null,
              ),
              const SizedBox(height: 32),

              ElevatedButton(
                onPressed: _isLoading ? null : _submit,
                style: ElevatedButton.styleFrom(padding: const EdgeInsets.symmetric(vertical: 16)),
                child: _isLoading
                    ? const SizedBox(height: 20, width: 20, child: CircularProgressIndicator(strokeWidth: 2, color: Colors.white))
                    : Text(_postType == 'job_offer' ? 'Post Job Offer' : 'Share Discussion'),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
