// ignore_for_file: deprecated_member_use
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:image_picker/image_picker.dart';
import 'package:intl/intl.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import 'package:tailorsync_v2/core/notifications/notification_service.dart';
import 'package:tailorsync_v2/features/customers/models/customer.dart';
import 'package:tailorsync_v2/features/customers/repositories/customer_repository.dart';
import 'package:tailorsync_v2/features/jobs/models/job_model.dart';
import 'package:tailorsync_v2/features/jobs/repositories/job_repository.dart';

class CreateJobScreen extends ConsumerStatefulWidget {
  const CreateJobScreen({super.key});

  @override
  ConsumerState<CreateJobScreen> createState() => _CreateJobScreenState();
}

class _CreateJobScreenState extends ConsumerState<CreateJobScreen> {
  final _formKey = GlobalKey<FormState>();
  final _titleController = TextEditingController();
  final _priceController = TextEditingController();
  final _balanceController = TextEditingController();
  final _notesController = TextEditingController();
  
  DateTime? _dueDate;
  Customer? _selectedCustomer;
  final List<XFile> _selectedImages = [];
  bool _isLoading = false;

  // Measurement editing
  Map<String, dynamic> _tempMeasurements = {};

  @override
  void dispose() {
    _titleController.dispose();
    _priceController.dispose();
    _balanceController.dispose();
    _notesController.dispose();
    super.dispose();
  }

  Future<void> _pickImages() async {
    final ImagePicker picker = ImagePicker();
    final List<XFile> images = await picker.pickMultiImage();
    if (images.isNotEmpty) {
      setState(() {
        _selectedImages.addAll(images);
      });
    }
  }

  Future<void> _selectDate(BuildContext context) async {
    final DateTime? picked = await showDatePicker(
      context: context,
      initialDate: DateTime.now().add(const Duration(days: 7)),
      firstDate: DateTime.now(),
      lastDate: DateTime.now().add(const Duration(days: 365)),
    );
    if (picked != null && picked != _dueDate) {
      setState(() {
        _dueDate = picked;
      });
    }
  }

  void _onCustomerSelected(Customer? customer) {
    setState(() {
      _selectedCustomer = customer;
      _tempMeasurements = Map.from(customer?.measurements ?? {});
    });
  }

  Future<void> _saveJob({required bool isQuote}) async {
    if (!_formKey.currentState!.validate()) return;
    if (_selectedCustomer == null) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please select a customer')),
      );
      return;
    }
    if (_dueDate == null && !isQuote) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(content: Text('Please select a due date')),
      );
      return;
    }

    setState(() => _isLoading = true);

    try {
      // 1. Upload Images
      List<String> imageUrls = [];
      if (_selectedImages.isNotEmpty) {
        final storage = Supabase.instance.client.storage.from('job_images');
        for (var i = 0; i < _selectedImages.length; i++) {
          final file = _selectedImages[i];
          final timestamp = DateTime.now().millisecondsSinceEpoch;
          final userId = Supabase.instance.client.auth.currentUser!.id;
          final path = '$userId/$timestamp$i.jpg';
          
          await storage.upload(path, File(file.path));
          final url = storage.getPublicUrl(path);
          imageUrls.add(url);
        }
      }

      // 2. Update Customer Measurements if changed
      if (_selectedCustomer != null && _tempMeasurements.isNotEmpty) {
        final updatedCustomer = _selectedCustomer!.copyWith(measurements: _tempMeasurements);
        // Only update if measurements actually changed? checking equatability might be overkill here
        // Just always update for now to ensure latest are saved.
        await ref.read(customerRepositoryProvider.notifier).updateCustomer(updatedCustomer);
      }

      // 3. Create Job
      final job = JobModel(
        id: '', // Generated by DB (but we pass empty string here, handled by repo/db)
        userId: Supabase.instance.client.auth.currentUser!.id,
        customerId: _selectedCustomer!.id!,
        title: _titleController.text,
        price: double.tryParse(_priceController.text) ?? 0,
        balanceDue: double.tryParse(_balanceController.text) ?? 0,
        dueDate: _dueDate ?? DateTime.now(), // Default for quotes if null?
        status: isQuote ? 'quote' : 'pending',
        images: imageUrls,
        notes: _notesController.text,
        createdAt: DateTime.now(),
      );

      await ref.read(jobRepositoryProvider.notifier).createJob(job);
      
      // 4. Schedule Notification (if it's an order)
      if (!isQuote && _dueDate != null) {
        final notificationId = DateTime.now().millisecondsSinceEpoch ~/ 1000;
        await NotificationService.scheduleNotification(
          id: notificationId,
          title: 'Job Due: ${job.title}',
          body: 'Order for ${_selectedCustomer!.fullName} is due today!',
          scheduledDate: _dueDate!,
        );
      }

      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text(isQuote ? 'Quote saved!' : 'Order created!')),
        );
        await Future.delayed(const Duration(milliseconds: 50));
        if (mounted) Navigator.pop(context);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('Error: $e')),
        );
      }
    } finally {
      if (mounted) setState(() => _isLoading = false);
    }
  }

  @override
  Widget build(BuildContext context) {


    return Scaffold(
      appBar: AppBar(title: const Text('New Order / Quote')),
      body: SingleChildScrollView(
        padding: const EdgeInsets.all(16.0),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // --- Customer Selection ---
              _buildCustomerDropdown(),
              const SizedBox(height: 16),
              
              // --- Measurements Expansion ---
              if (_selectedCustomer != null) _buildMeasurementsSection(),
              const SizedBox(height: 16),

              // --- Title ---
              TextFormField(
                controller: _titleController,
                decoration: const InputDecoration(
                  labelText: 'Order Title',
                  hintText: 'e.g., Wedding Suit, 3-Piece Kaftan',
                  border: OutlineInputBorder(),
                ),
                validator: (v) => v?.isEmpty == true ? 'Required' : null,
              ),
              const SizedBox(height: 16),

              // --- Price & Balance ---
              Row(
                children: [
                  Expanded(
                    child: TextFormField(
                      controller: _priceController,
                      keyboardType: TextInputType.number,
                      decoration: const InputDecoration(
                        labelText: 'Price',
                        prefixText: '₦ ',
                        border: OutlineInputBorder(),
                      ),
                      onChanged: (val) {
                        // Auto-fill balance if empty
                        if (_balanceController.text.isEmpty) {
                          _balanceController.text = val;
                        }
                      },
                      validator: (v) => v?.isEmpty == true ? 'Required' : null,
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: TextFormField(
                      controller: _balanceController,
                      keyboardType: TextInputType.number,
                      decoration: const InputDecoration(
                        labelText: 'Balance Due',
                        prefixText: '₦ ',
                        border: OutlineInputBorder(),
                      ),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),

              // --- Due Date ---
              InkWell(
                onTap: () => _selectDate(context),
                child: InputDecorator(
                  decoration: const InputDecoration(
                    labelText: 'Due Date',
                    border: OutlineInputBorder(),
                    suffixIcon: Icon(Icons.calendar_today),
                  ),
                  child: Text(
                    _dueDate == null
                        ? 'Select Date'
                        : DateFormat.yMMMd().format(_dueDate!),
                  ),
                ),
              ),
              const SizedBox(height: 16),

              // --- Images ---
              _buildImagePicker(),
              const SizedBox(height: 16),

              // --- Notes ---
              TextFormField(
                controller: _notesController,
                maxLines: 3,
                decoration: const InputDecoration(
                  labelText: 'Notes',
                  border: OutlineInputBorder(),
                ),
              ),
              const SizedBox(height: 24),

              // --- Actions ---
              Row(
                children: [
                  Expanded(
                    child: OutlinedButton(
                      onPressed: _isLoading ? null : () => _saveJob(isQuote: true),
                      style: OutlinedButton.styleFrom(padding: const EdgeInsets.symmetric(vertical: 16)),
                      child: const Text('Save as Quote'),
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: ElevatedButton(
                      onPressed: _isLoading ? null : () => _saveJob(isQuote: false),
                      style: ElevatedButton.styleFrom(
                        backgroundColor: const Color(0xFF5D3FD3),
                        foregroundColor: Colors.white,
                        padding: const EdgeInsets.symmetric(vertical: 16),
                      ),
                      child: _isLoading 
                          ? const CircularProgressIndicator(color: Colors.white) 
                          : const Text('Create Order'),
                    ),
                  ),
                ],
              ),
            ],
          ),
        ),
      ),
    );
  }

  Widget _buildCustomerDropdown() {
    // You might want to use a Autocomplete or a Modal for better UX with many customers
    return Consumer(
      builder: (context, ref, _) {
        final customersAsync = ref.watch(customerRepositoryProvider);
        
        return customersAsync.when(
          data: (customers) {
            return DropdownButtonFormField<Customer>(
              decoration: const InputDecoration(
                labelText: 'Select Customer',
                border: OutlineInputBorder(),
              ),
              value: _selectedCustomer,
              items: customers.map((c) => DropdownMenuItem(
                value: c,
                child: Text(c.fullName),
              )).toList(),
              onChanged: _onCustomerSelected,
            );
          },
          loading: () => const LinearProgressIndicator(),
          error: (err, _) => Text('Error loading customers: $err'),
        );
      },
    );
  }

  Widget _buildMeasurementsSection() {
    return Card(
      child: ExpansionTile(
        title: const Text('Measurements'),
        subtitle: const Text('Tap to edit for this order'),
        children: [
          Padding(
            padding: const EdgeInsets.all(16.0),
            child: Column(
              children: [
                // List existing
                ..._tempMeasurements.entries.map((e) => _buildMeasurementRow(e.key, e.value.toString())),
                
                // Add new
                const SizedBox(height: 8),
                TextButton.icon(
                  onPressed: () {
                    _showAddMeasurementDialog();
                  },
                  icon: const Icon(Icons.add),
                  label: const Text('Add Measurement Field'),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildMeasurementRow(String key, String value) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 8.0),
      child: Row(
        children: [
          Expanded(child: Text("$key:", style: const TextStyle(fontWeight: FontWeight.bold))),
          Expanded(
            child: TextFormField(
              initialValue: value,
              decoration: const InputDecoration(
                isDense: true,
                contentPadding: EdgeInsets.symmetric(horizontal: 8, vertical: 8),
                border: OutlineInputBorder(),
              ),
              onChanged: (val) {
                _tempMeasurements[key] = val;
              },
            ),
          ),
        ],
      ),
    );
  }

  Future<void> _showAddMeasurementDialog() async {
    String key = '';
    String value = '';
    
    await showDialog(
      context: context,
      builder: (context) => AlertDialog(
        title: const Text('Add Measurement'),
        content: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            TextField(
              decoration: const InputDecoration(labelText: 'Name (e.g. Waist)'),
              onChanged: (v) => key = v,
            ),
            TextField(
              decoration: const InputDecoration(labelText: 'Value (e.g. 32)'),
              onChanged: (v) => value = v,
            ),
          ],
        ),
        actions: [
          TextButton(onPressed: () => Navigator.pop(context), child: const Text('Cancel')),
          TextButton(
            onPressed: () {
              if (key.isNotEmpty) {
                setState(() {
                  _tempMeasurements[key] = value;
                });
                Navigator.pop(context);
              }
            },
            child: const Text('Add'),
          ),
        ],
      ),
    );
  }

  Widget _buildImagePicker() {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        const Text('Design Images / Sketches', style: TextStyle(fontWeight: FontWeight.bold)),
        const SizedBox(height: 8),
        SizedBox(
          height: 100,
          child: ListView(
            scrollDirection: Axis.horizontal,
            children: [
              InkWell(
                onTap: _pickImages,
                child: Container(
                  width: 80,
                  height: 80,
                  decoration: BoxDecoration(
                    color: Colors.grey[200],
                    borderRadius: BorderRadius.circular(8),
                    border: Border.all(color: Colors.grey),
                  ),
                  child: const Icon(Icons.camera_alt, color: Colors.grey),
                ),
              ),
              const SizedBox(width: 8),
              ..._selectedImages.map((file) => Padding(
                padding: const EdgeInsets.only(right: 8.0),
                child: ClipRRect(
                  borderRadius: BorderRadius.circular(8),
                  child: Image.file(File(file.path), width: 80, height: 80, fit: BoxFit.cover),
                ),
              )),
            ],
          ),
        ),
      ],
    );
  }
}
